version: "3.7"

services:
  hamachi:
    image: hamachi:2.1.0
    build: .
    container_name: hamachi
    network_mode: host
    privileged: true
#   environment:
#     ACCOUNT:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/var/lib/logmein-hamachi:rw
    command:
      - bash
      - startup.sh
